// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb1oCA_tMhiWSo46ikvxe8I_owRD0gtI0',
    appId: '1:919828842770:web:fe8888142570469ab3cbcb',
    messagingSenderId: '919828842770',
    projectId: 'saylani-devathon-sumit',
    authDomain: 'saylani-devathon-sumit.firebaseapp.com',
    storageBucket: 'saylani-devathon-sumit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBEmsmKxTzIjBMF7amJ1R_7VjvSe4zy_o',
    appId: '1:919828842770:android:f15f0df3d947efa5b3cbcb',
    messagingSenderId: '919828842770',
    projectId: 'saylani-devathon-sumit',
    storageBucket: 'saylani-devathon-sumit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1HhgmK4ORt_cEljoI_gk8rM99GeURucw',
    appId: '1:919828842770:ios:138cb153c44183b8b3cbcb',
    messagingSenderId: '919828842770',
    projectId: 'saylani-devathon-sumit',
    storageBucket: 'saylani-devathon-sumit.appspot.com',
    iosBundleId: 'com.example.expoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1HhgmK4ORt_cEljoI_gk8rM99GeURucw',
    appId: '1:919828842770:ios:a7681713e887835cb3cbcb',
    messagingSenderId: '919828842770',
    projectId: 'saylani-devathon-sumit',
    storageBucket: 'saylani-devathon-sumit.appspot.com',
    iosBundleId: 'com.example.expoProject.RunnerTests',
  );
}
